### ISSUE TITLE
Feedback A01

### ISSUE THREAD

**Issue by AnnaLotz** [Cari1512/EIA2#1]
- bitte im Steckbrief einen direkten Link zu diesem Repository hinzufügen
Aktivitätsdiagramm sieht sehr gut aus, lediglich ein paar Kleinigkeiten muss ich anmerken:  
- was muss nach dem continue mit i passieren?
- die Bedingungen im switch müssten etwas genauer aussehen. Nur [0] ist keine richtige Angabe. Es müsste beispielsweise heißen [i=0]
- was genau muss auf dem Weg nach links nach dem Aufruf von `CreateBox` noch passieren? Sonst stellt es keinen Durchlauf vom Array dar.

**Comment by Cari1512** [comment]
Hallo Anna, 
danke für die Rückmeldung!
Zum letzten Punkt hätte ich noch eine Frage: wie genau beschreibe ich das die nächste Stelle vom size[ ] Array genommen wird. Normalerweise hätte ich i++ geschrieben, aber da es hier schon i als Variable gibt, weiß ich nicht man kurz und knackig beschreibt ,dass der Index im size[ ] Array hochgezählt wird.

**Comment by AnnaLotz** [comment]
> Index im size[ ] Array hochgezählt

Du kannst das theoretisch genau so dort rein schreiben. In Aktivitätsdiagrammen kann man auch Prosa schreiben, vor allem dann, wenn du nicht genau weißt, wie man das in "Code-Sprache" schreiben kann.

**Comment by Cari1512** [comment]
Ok, Ich habs jetzt verbessert ^^
Danke schön!
